In [108]:
from tensorflow.keras.preprocessing.text import one_hot

In [109]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [110]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [111]:
## Define the vocabulary size
voc_size=10000

In [112]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [113]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[572, 4517, 3955, 6872],
 [572, 4517, 3955, 5701],
 [572, 4446, 3955, 4493],
 [8316, 7768, 72, 7712, 3628],
 [8316, 7768, 72, 7712, 1545],
 [3571, 572, 3836, 3955, 5039],
 [5176, 9497, 4055, 7712]]

In [114]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [115]:
import numpy as np

In [116]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  572 4517 3955 6872]
 [   0    0    0    0  572 4517 3955 5701]
 [   0    0    0    0  572 4446 3955 4493]
 [   0    0    0 8316 7768   72 7712 3628]
 [   0    0    0 8316 7768   72 7712 1545]
 [   0    0    0 3571  572 3836 3955 5039]
 [   0    0    0    0 5176 9497 4055 7712]]


In [117]:
## feature representation
dim=10

In [118]:
'''model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')'''

"model=Sequential()\nmodel.add(Embedding(voc_size,dim,input_length=sent_length))\nmodel.compile('adam','mse')"

In [119]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [120]:
model.build((None,sent_length))

In [121]:
'''model=Sequential()
model.add(Embedding(1000, 64))
model.compile('rmsprop', 'mse')'''

"model=Sequential()\nmodel.add(Embedding(1000, 64))\nmodel.compile('rmsprop', 'mse')"

In [122]:
model.summary()

Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_15 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [123]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[[ 3.65648605e-02, -1.54202580e-02,  1.34739019e-02,
          7.28491694e-03, -4.19589058e-02,  3.23791616e-02,
          2.41971500e-02,  4.97051366e-02, -7.26213306e-03,
         -1.88017488e-02],
        [ 3.65648605e-02, -1.54202580e-02,  1.34739019e-02,
          7.28491694e-03, -4.19589058e-02,  3.23791616e-02,
          2.41971500e-02,  4.97051366e-02, -7.26213306e-03,
         -1.88017488e-02],
        [ 3.65648605e-02, -1.54202580e-02,  1.34739019e-02,
          7.28491694e-03, -4.19589058e-02,  3.23791616e-02,
          2.41971500e-02,  4.97051366e-02, -7.26213306e-03,
         -1.88017488e-02],
        [ 3.65648605e-02, -1.54202580e-02,  1.34739019e-02,
          7.28491694e-03, -4.19589058e-02,  3.23791616e-02,
          2.41971500e-02,  4.97051366e-02, -7.26213306e-03,
         -1.88017488e-02],
        [-3.62859145e-02, -2.81678326e-02, -3.38182673e-02,
          1.43379830e-02, -2.69478559e-03,  9.25989076e-03,
          2.89007686e-02,  4.10058983e-02, -4.919290

In [124]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[[ 3.65648605e-02, -1.54202580e-02,  1.34739019e-02,
          7.28491694e-03, -4.19589058e-02,  3.23791616e-02,
          2.41971500e-02,  4.97051366e-02, -7.26213306e-03,
         -1.88017488e-02],
        [ 3.65648605e-02, -1.54202580e-02,  1.34739019e-02,
          7.28491694e-03, -4.19589058e-02,  3.23791616e-02,
          2.41971500e-02,  4.97051366e-02, -7.26213306e-03,
         -1.88017488e-02],
        [ 3.65648605e-02, -1.54202580e-02,  1.34739019e-02,
          7.28491694e-03, -4.19589058e-02,  3.23791616e-02,
          2.41971500e-02,  4.97051366e-02, -7.26213306e-03,
         -1.88017488e-02],
        [ 3.65648605e-02, -1.54202580e-02,  1.34739019e-02,
          7.28491694e-03, -4.19589058e-02,  3.23791616e-02,
          2.41971500e-02,  4.97051366e-02, -7.26213306e-03,
         -1.88017488e-02],
        [-3.62859145e-02, -2.81678326e-02, -3.38182673e-02,
          1.43379830e-02, -2.69478559e-03,  9.25989076e-03,
          2.89007686e-02,  4.10058983e-02, -4.919290

In [126]:
embedded_docs[0]

array([   0,    0,    0,    0,  572, 4517, 3955, 6872])

In [135]:
input_data = np.array([embedded_docs[0]])  # Ensure it's (1, sequence_length)
predictions = model.predict(input_data)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[[ 0.03656486 -0.01542026  0.0134739   0.00728492 -0.04195891
    0.03237916  0.02419715  0.04970514 -0.00726213 -0.01880175]
  [ 0.03656486 -0.01542026  0.0134739   0.00728492 -0.04195891
    0.03237916  0.02419715  0.04970514 -0.00726213 -0.01880175]
  [ 0.03656486 -0.01542026  0.0134739   0.00728492 -0.04195891
    0.03237916  0.02419715  0.04970514 -0.00726213 -0.01880175]
  [ 0.03656486 -0.01542026  0.0134739   0.00728492 -0.04195891
    0.03237916  0.02419715  0.04970514 -0.00726213 -0.01880175]
  [-0.03628591 -0.02816783 -0.03381827  0.01433798 -0.00269479
    0.00925989  0.02890077  0.0410059  -0.04919291 -0.04184673]
  [-0.02461456  0.04603847 -0.02201661  0.03249054 -0.0271081
    0.01541256 -0.00977711  0.03208167  0.00758562 -0.02977146]
  [-0.00491368 -0.04180676  0.03858789 -0.00927147  0.00176815
   -0.00582048  0.02608636  0.0494845   0.01284256  0.01136022]
  [ 0.00129304  0.00703739  0.01787532 -0.00453625 -0.03765965
    0.00648

In [ ]:
##model.predict(embedded_docs[0])